services:
 nginx:
  build : ./vite-project
  networks:
   - cloud-ai
  ports:
   - "80:80"
  volumes:
   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
 
 backend:
  build : ./backend
  networks:
   - cloud-ai
  ports:
   - "4000:4000"
  restart: always
  env_file:
   - ./backend/.env
  
 redis:
  image: redis:alpine
  networks:
   - cloud-ai
  ports:
   - "6379:6379"
  volumes:
   - redis-data:/data
 postgres:
  image : postgres:17-alpine
  networks:
   - cloud-ai
  ports:
   - "5432:5432"
  environment:
    POSTGRES_USER: zakaria
    POSTGRES_PASSWORD: 1992
    POSTGRES_DB: cloud_ai
  volumes:
   - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
   - pgdata:/var/lib/postgresql/data
  # cloudflare:
  #  image : cloudflare/cloudflared:latest
  #  command: tunnel --no-autoupdate run --token eyJhIjoiMmJlNzMzZjE2YzE3NDc0YjMyZmU1ZGJmZGE4NmNiM2YiLCJ0IjoiMDdkMTZiN2YtNDU0Yy00MzBjLTk2Y2EtYWU0ZTFhYjg2Y2RiIiwicyI6IlltWTFOall3WlRJdE1UWm1aaTAwWmpRMExXSTNNRGd0TXpVNVlUQTROVGN4TURRMCJ9
  #  restart : unless-stopped
volumes:
 redis-data:
 pgdata:
networks:
 cloud-ai: